import { typescript, TextFile } from 'projen';
import { GithubCredentials } from 'projen/lib/github';

const minNodeVersion = '20.19.0';

const project = new typescript.TypeScriptProject({
  name: '@jjrawlins/cfn-drift-remediate',
  description: 'CLI tool to remediate CloudFormation drift by re-importing drifted resources with their actual state',
  packageName: '@jjrawlins/cfn-drift-remediate',
  authorName: 'Jayson Rawlins',
  authorEmail: 'jayson.rawlins@gmail.com',
  license: 'Apache-2.0',
  repository: 'https://github.com/JaysonRawlins/cfn-drift-remediate.git',
  defaultReleaseBranch: 'main',
  minNodeVersion: minNodeVersion,
  projenrcTs: true,

  // CLI bin entry point
  bin: {
    'cfn-drift-remediate': 'lib/index.js',
  },

  // NPM Publishing disabled for beta — re-enable when ready for public release
  releaseToNpm: false,

  // GitHub Options
  githubOptions: {
    projenCredentials: GithubCredentials.fromApp({
      appIdSecret: 'PROJEN_APP_ID',
      privateKeySecret: 'PROJEN_APP_PRIVATE_KEY',
    }),
    mergify: false,
    pullRequestLintOptions: {
      semanticTitleOptions: {
        types: ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'chore', 'revert', 'ci', 'build', 'deps', 'wip', 'release'],
      },
    },
  },

  // Runtime Dependencies
  deps: [
    '@aws-sdk/client-cloudformation',
    '@aws-sdk/credential-providers',
    'commander',
    'yaml-cfn',
    'chalk',
    'ora',
    '@inquirer/prompts',
  ],

  // Dev Dependencies
  devDeps: [
    '@types/node',
    '@types/js-yaml',
  ],

  // TypeScript configuration
  tsconfig: {
    compilerOptions: {
      esModuleInterop: true,
      types: ['node'],
    },
  },
  tsconfigDev: {
    compilerOptions: {
      types: ['node', 'jest'],
    },
  },

  // Jest configuration - exclude integration tests by default
  jestOptions: {
    jestConfig: {
      testPathIgnorePatterns: ['/node_modules/', '/test/integration/'],
    },
  },
});

// NOTE: When re-enabling npm publishing, restore these overrides:
// - npmAccess: NpmAccess.PUBLIC
// - releaseToNpm: true
// - npmTrustedPublishing: true
// - Node 24 override for release_npm job
// - OIDC permissions for release_npm job

// .tool-versions file for asdf
new TextFile(project, '.tool-versions', {
  lines: [
    '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
    `nodejs ${minNodeVersion}`,
    'yarn 1.22.22',
  ],
});

// Ignore runtime backup files created by cfn-drift-remediate
project.gitignore.addPatterns('.cfn-drift-remediate-backup-*');
project.npmignore?.addPatterns('.cfn-drift-remediate-backup-*');

project.synth();
