import { typescript, TextFile, YamlFile } from 'projen';
import { Dependabot, DependabotScheduleInterval, GithubCredentials, VersioningStrategy } from 'projen/lib/github';
import { NpmAccess } from 'projen/lib/javascript';

const minNodeVersion = '20.19.0';

const project = new typescript.TypeScriptProject({
  name: '@jjrawlins/cfn-drift-remediate',
  description: 'CLI tool to remediate CloudFormation drift by re-importing drifted resources with their actual state',
  packageName: '@jjrawlins/cfn-drift-remediate',
  authorName: 'Jayson Rawlins',
  authorEmail: 'jayson.rawlins@gmail.com',
  license: 'Apache-2.0',
  repository: 'https://github.com/JaysonRawlins/cfn-drift-remediate.git',
  defaultReleaseBranch: 'main',
  minNodeVersion: minNodeVersion,
  projenrcTs: true,

  // CLI bin entry point
  bin: {
    'cfn-drift-remediate': 'lib/index.js',
  },

  // NPM Publishing via OIDC trusted publishing (beta dist-tag)
  releaseToNpm: true,
  npmAccess: NpmAccess.PUBLIC,
  npmTrustedPublishing: true,

  // Dependency upgrades are handled by Dependabot (lockfile-only + cooldown).
  // projen still owns package.json; major version bumps stay as manual .projenrc.ts edits.
  depsUpgrade: false,

  // Frozen-lockfile in CI so Dependabot lockfile-only PRs don't trigger cosmetic self-mutation.
  buildWorkflowOptions: {
    mutableBuild: false,
  },

  // GitHub Options
  githubOptions: {
    projenCredentials: GithubCredentials.fromApp({
      appIdSecret: 'PROJEN_APP_ID',
      privateKeySecret: 'PROJEN_APP_PRIVATE_KEY',
    }),
    mergify: false,
    pullRequestLintOptions: {
      semanticTitleOptions: {
        types: ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'chore', 'revert', 'ci', 'build', 'deps', 'wip', 'release'],
      },
    },
  },

  // Runtime Dependencies
  deps: [
    '@aws-sdk/client-cloudcontrol',
    '@aws-sdk/client-cloudformation',
    '@aws-sdk/client-s3',
    '@aws-sdk/client-sts',
    '@aws-sdk/credential-providers',
    'commander',
    'yaml-cfn',
    'chalk',
    'ora',
    '@inquirer/prompts',
  ],

  // Dev Dependencies
  devDeps: [
    '@types/node',
    '@types/js-yaml',
  ],

  // TypeScript configuration
  tsconfig: {
    compilerOptions: {
      esModuleInterop: true,
      skipLibCheck: true,
      types: ['node'],
    },
  },
  tsconfigDev: {
    compilerOptions: {
      types: ['node', 'jest'],
    },
  },

  // Jest configuration - exclude integration tests by default
  jestOptions: {
    jestConfig: {
      testPathIgnorePatterns: ['/node_modules/', '/test/integration/'],
    },
  },
});

// Release workflow overrides for OIDC trusted publishing
const releaseWorkflow = project.github!.tryFindWorkflow('release')!;
releaseWorkflow.file!.addOverride('jobs.release.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release.permissions.contents', 'write');
releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.id-token', 'write');
releaseWorkflow.file!.addOverride('jobs.release_npm.permissions.contents', 'write');
// Override node-version to 24 for npm trusted publishing (requires npm 11.5.1+)
releaseWorkflow.file!.addOverride('jobs.release_npm.steps.0.with.node-version', '24');
// Set registry-url so setup-node configures .npmrc for OIDC token exchange
releaseWorkflow.file!.addOverride('jobs.release_npm.steps.0.with.registry-url', 'https://registry.npmjs.org');

// .tool-versions file for asdf
new TextFile(project, '.tool-versions', {
  lines: [
    '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".',
    `nodejs ${minNodeVersion}`,
    'yarn 1.22.22',
  ],
});

// Exclude integration test CDK app from ESLint (has its own dependencies)
project.eslint?.addIgnorePattern('test/integration/');

// Ignore runtime backup files created by cfn-drift-remediate

project.gitignore?.addPatterns(
  '.cfn-drift-remediate-backup-*',
  'plan.json',
);
project.npmignore?.addPatterns('.cfn-drift-remediate-backup-*');

// Dependabot — lockfile-only, patch+minor only, cooldown before PRs open.
// Patches the raw config because projen's Dependabot API doesn't yet expose
// cooldown, ignore.update-types, or multi-ecosystem entries.
const dependabot = new Dependabot(project.github!, {
  scheduleInterval: DependabotScheduleInterval.WEEKLY,
  versioningStrategy: VersioningStrategy.LOCKFILE_ONLY,
  labels: ['dependencies'],
  openPullRequestsLimit: 10,
});

const npmUpdate = dependabot.config.updates[0];
npmUpdate.cooldown = {
  'default-days': 7,
  'semver-minor-days': 7,
  'semver-patch-days': 3,
  'include': ['*'],
};
// Replace projen's lazy-resolved ignore with a static array.
// Keeps the projen ignore (anti-tamper boundary) and blocks major bumps globally.
npmUpdate.ignore = [
  { 'dependency-name': 'projen' },
  { 'dependency-name': '*', 'update-types': ['version-update:semver-major'] },
];

// github-actions ecosystem is kept enabled for SECURITY ALERTS ONLY.
// Version-update PRs are disabled (open-pull-requests-limit: 0) because
// Dependabot would have to edit projen-generated workflow files directly,
// which trips projen's anti-tamper check (the files get regenerated on
// synth from .projenrc.ts). Empirically confirmed via PR #19 on this repo.
// To bump action versions, use project.github.actions.set() in .projenrc.ts
// or wait for a projen release that bumps its internal defaults.
dependabot.config.updates.push({
  'package-ecosystem': 'github-actions',
  'directory': '/',
  'schedule': { interval: 'weekly' },
  'open-pull-requests-limit': 0,
  'labels': ['dependencies', 'github-actions'],
});

// Security gate on PRs — calls the reusable osv-scanner workflow from
// JaysonRawlins/.github. Fails on CVSS >= 9.0. Portable alternative to
// dependency-review-action for repos without Advanced Security.
new YamlFile(project, '.github/workflows/security.yml', {
  obj: {
    name: 'security',
    on: {
      pull_request: {},
      workflow_dispatch: {},
    },
    jobs: {
      security: {
        uses: 'JaysonRawlins/.github/.github/workflows/security.yml@main',
      },
    },
  },
});

project.synth();
